package com.dayanghome.dayangerp.constant;

public class CityData {
    public static final String demo = "{\n" +
            "  \"lanzhou\":[{\n" +
            "    \"cityId\":123,\n" +
            "    \"cityName\":\"123\"\n" +
            "  },{\n" +
            "    \"cityId\":1234,\n" +
            "    \"cityName\":\"1234\"\n" +
            "  }\n" +
            "  ]\n" +
            "}";


    public static final String province_json = "[\n" +
            "    {\n" +
            "        provinceId: 610000,\n" +
            "        provinceName:\"陕西\"\n" +
            "    },\n" +
            "    {\n" +
            "        provinceId: 620000,\n" +
            "        provinceName:\"甘肃\"\n" +
            "    },\n" +
            "    {\n" +
            "        provinceId: 630000,\n" +
            "        provinceName:\"青海\"\n" +
            "    },\n" +
            "    {\n" +
            "        provinceId: 640000,\n" +
            "        provinceName:\"宁夏\"\n" +
            "    },\n" +
            "    {\n" +
            "        provinceId: 650000,\n" +
            "        provinceName:\"新疆\"\n" +
            "    }\n" +
            "]";

    public static final String city_json = "{\n" +
            "    610000 : [\n" +
            "        {\n" +
            "            cityId:610100,\n" +
            "            cityName:\"西安市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:610200,\n" +
            "            cityName:\"铜川市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:610300,\n" +
            "            cityName:\"宝鸡市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:610400,\n" +
            "            cityName:\"咸阳市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:610500,\n" +
            "            cityName:\"渭南市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:610600,\n" +
            "            cityName:\"延安市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:610700,\n" +
            "            cityName:\"汉中市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:610800,\n" +
            "            cityName:\"榆林市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:610900,\n" +
            "            cityName:\"安康市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:611000,\n" +
            "            cityName:\"商洛市\"\n" +
            "        }\n" +
            "    ],\n" +
            "    620000 : [\n" +
            "        {\n" +
            "            cityId:620100,\n" +
            "            cityName:\"兰州市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:620200,\n" +
            "            cityName:\"嘉峪关市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:620300,\n" +
            "            cityName:\"金昌市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:620400,\n" +
            "            cityName:\"白银市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:620500,\n" +
            "            cityName:\"天水市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:620600,\n" +
            "            cityName:\"武威市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:620700,\n" +
            "            cityName:\"张掖市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:620800,\n" +
            "            cityName:\"平凉市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:620900,\n" +
            "            cityName:\"酒泉市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:621000,\n" +
            "            cityName:\"庆阳市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:621100,\n" +
            "            cityName:\"定西市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:621200,\n" +
            "            cityName:\"陇南市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:622900,\n" +
            "            cityName:\"临夏自治州\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:623000,\n" +
            "            cityName:\"甘南自治州\"\n" +
            "        }\n" +
            "    ],\n" +
            "    630000 : [\n" +
            "        {\n" +
            "            cityId:630100,\n" +
            "            cityName:\"西宁市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:632100,\n" +
            "            cityName:\"海东市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:632200,\n" +
            "            cityName:\"海北市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:632300,\n" +
            "            cityName:\"黄南自治州\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:632500,\n" +
            "            cityName:\"海南自治州\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:632600,\n" +
            "            cityName:\"果洛自治州\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:632700,\n" +
            "            cityName:\"玉树自治州\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:632800,\n" +
            "            cityName:\"海西自治州\"\n" +
            "        }\n" +
            "    ],\n" +
            "    640000 : [\n" +
            "        {\n" +
            "            cityId:640100,\n" +
            "            cityName:\"银川市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:640200,\n" +
            "            cityName:\"石嘴山\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:640300,\n" +
            "            cityName:\"吴忠市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:640400,\n" +
            "            cityName:\"固原市\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:640500,\n" +
            "            cityName:\"中卫市\"\n" +
            "        }\n" +
            "    ],\n" +
            "    650000 : [\n" +
            "        {\n" +
            "            cityId:650100,\n" +
            "            cityName:\"乌鲁木齐\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:650200,\n" +
            "            cityName:\"克拉玛依\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:652100,\n" +
            "            cityName:\"吐鲁番\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:652200,\n" +
            "            cityName:\"哈密\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:652300,\n" +
            "            cityName:\"昌吉\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:652700,\n" +
            "            cityName:\"博尔塔拉\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:652800,\n" +
            "            cityName:\"巴音郭楞\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:652900,\n" +
            "            cityName:\"阿克苏\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:653000,\n" +
            "            cityName:\"克孜勒苏\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:653100,\n" +
            "            cityName:\"喀什\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:653200,\n" +
            "            cityName:\"和田\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:654000,\n" +
            "            cityName:\"伊犁\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:654200,\n" +
            "            cityName:\"塔城\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:654300,\n" +
            "            cityName:\"阿勒泰\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:659001,\n" +
            "            cityName:\"石河子\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:659002,\n" +
            "            cityName:\"阿拉尔\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:659003,\n" +
            "            cityName:\"图木舒克\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:659004,\n" +
            "            cityName:\"五家渠\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:659005,\n" +
            "            cityName:\"北屯\"\n" +
            "        },\n" +
            "        {\n" +
            "            cityId:659006,\n" +
            "            cityName:\"铁门关\"\n" +
            "        }\n" +
            "    ]\n" +
            "}";
}
